# All commands are intended to be run as the 'robot' user
---
- name: add the public key to the authorized keys
  authorized_key:
    user: "{{ robot_name }}"
    key: "{{ item }}"
  with_file:
    - robot_id_rsa.pub
  remote_user: "{{ robot_name  }}"
  notify:
    - restart sshd
  tags: sshd

- name: install public key for robot user
  copy:
    src: robot_id_rsa.pub
    dest: /home/{{ robot_name }}/.ssh/
    mode: 0644
  remote_user: "{{ robot_name  }}"

- name: install private key for robot user
  copy:
    src: robot_id_rsa
    dest: /home/{{ robot_name }}/.ssh/
    mode: 0600
  remote_user: "{{ robot_name  }}"
