---
tags:
  - training
  - workouts
  - exercises
parameters:
  workoutParam:
    name: workout_id
    type: string
    in: path
    required: true
    description: The id of the workout to retrieve.
  setParam:
    name: set_id
    type: string
    in: path
    required: true
    description: The id of a set to retrieve.
  exerciseParam:
    name: exercise_id
    type: string
    in: path
    required: true
    description: The id of a exercise to retrieve.

# URL routes for this api
paths:
  /exercises:
    get:
      summary: Get an ExerciseMeta array.
      description: Retrieve a paginated array of all of our exercises
      parameters:
        - "$ref": "#/parameters/pageParam"
      responses:
        200:
          description: An array of ExerciseMeta resources
          schema:
            type: array
            items:
              $ref: '#/definitions/ExerciseMeta'
        default:
            description: Unexpected error
            schema:
              $ref: '#/definitions/Error'
  /exercises/{name}:
    get:
      summary: Get an ExerciseMeta.
      description: Retrieve detailed information about a specific ExerciseMeta.
      parameters:
        - name: name
          in: path
          description: The name of the ExerciseMeta to retrieve
          required: true
          type: string
      responses:
        200:
          description: An ExerciseMeta resource
          schema:
            $ref: '#/definitions/ExerciseMeta'
        default:
            description: Unexpected error
            schema:
              $ref: '#/definitions/Error'
  /workouts:
    post: # Generate a new workout
      summary: Create a Workout.
      description: Generate a new workout for the provided muscle group.
      parameters:
        - name: muscle_group
          in: body
          description: The muscle group you would like to generate a workout for.
          required: true
          type: string
      responses:
        200:
          description: The newly generated workout.
          schema:
            $ref: '#/definitions/Workout'
        default:
            description: Unexpected error
            schema:
              $ref: '#/definitions/Error'
    get: # Get a list of workouts
      summary: Get an Workout array.
      description: Retrieve a paginated array of the most recently performed workouts.
      parameters:
        - "$ref": "#/parameters/pageParam"
      responses:
        200:
          description: An array of Workout resources
          schema:
            type: array
            items:
              $ref: '#/definitions/Workout'
        default:
            description: Unexpected error
            schema:
              $ref: '#/definitions/Error'
  /workouts/{workout_id}:
    get: # Retrieve the specified workout
      summary: Get a Workout.
      description: Retrieve the specified workout.
      parameters:
        - "$ref": "#/parameters/workoutParam"
      responses:
        200:
          description: The requested workout.
          schema:
            $ref: '#/definitions/Workout'
        default:
            description: Unexpected error
            schema:
              $ref: '#/definitions/Error'
    put: # Update the specified workout
      summary: Update a Workout.
      description: Update the specified workout.
      parameters:
        - "$ref": "#/parameters/workoutParam"
        - name: comment
          in: formData
          description: Any comment you would like to store for this Workout.
          required: false
          type: string
      responses:
        200:
          description: The updated workout.
          schema:
            $ref: '#/definitions/Workout'
        default:
            description: Unexpected error
            schema:
              $ref: '#/definitions/Error'
    delete: # Delete the specifieid workout
      summary: Delete a Workout.
      description: Delete the specified workout.
      parameters:
        - "$ref": "#/parameters/workoutParam"
      responses:
        200:
          description: Workout deleted.
        default:
            description: Unexpected error
            schema:
              $ref: '#/definitions/Error'
  /workouts/{workout_id}/sets:
    get: # Get all of the sets under the specified workout
      summary: Get an array of sets.
      description: Retrieve a paginated array of all sets under a specific workout.
      responses:
        200:
          description: An array of Set resources
          schema:
            type: array
            items:
              $ref: '#/definitions/Set'
        default:
            description: Unexpected error
            schema:
              $ref: '#/definitions/Error'
  /workouts/{workout_id}/sets/{set_id}:
    get: # Get the specified set
      summary: Get a Set.
      description: Retrieve the specified set.
      parameters:
        - "$ref": "#/parameters/workoutParam"
        - "$ref": "#/parameters/setParam"
      responses:
        200:
          description: The requested set.
          schema:
            $ref: '#/definitions/Set'
        default:
            description: Unexpected error
            schema:
              $ref: '#/definitions/Error'
    put: # Update the specified set
      summary: Update a Set.
      description: Update the specified set.
      parameters:
        - "$ref": "#/parameters/workoutParam"
        - "$ref": "#/parameters/setParam"
        - name: completed_at
          in: formData
          description: UTC timestamp of when this set was completed
          required: false
          type: boolean
      responses:
        200:
          description: The updated set.
          schema:
            $ref: '#/definitions/Set'
        default:
            description: Unexpected error
            schema:
              $ref: '#/definitions/Error'
    delete: # Delete the specified set
      summary: Delete a set.
      description: Delete the specified Set.
      parameters:
        - "$ref": "#/parameters/workoutParam"
        - "$ref": "#/parameters/setParam"
      responses:
        200:
          description: Set deleted.
        default:
            description: Unexpected error
            schema:
              $ref: '#/definitions/Error'
  /workouts/{workout_id}/sets/{set_id}/exercises:
    get: # All all exercises under the specified set
      summary: Get an array of exercises.
      description: Retrieve a paginated array of all exercises under a specific set.
      responses:
        200:
          description: An array of Exercise resources
          schema:
            type: array
            items:
              $ref: '#/definitions/Exercise'
        default:
            description: Unexpected error
            schema:
              $ref: '#/definitions/Error'
  /workouts/{workout_id}/sets/{set_id}/exercises/{exercise_id}:
    get: # Get the specified exercise
      summary: Get an Exercise.
      description: Retrieve the specified exercise.
      parameters:
        - "$ref": "#/parameters/workoutParam"
        - "$ref": "#/parameters/setParam"
        - "$ref": "#/parameters/exerciseParam"
      responses:
        200:
          description: The requested exercise.
          schema:
            $ref: '#/definitions/Exercise'
        default:
            description: Unexpected error
            schema:
              $ref: '#/definitions/Error'
    put: # Update the specified exercise
      summary: Update an Exercise.
      description: Update the specified exercise.
      parameters:
        - "$ref": "#/parameters/workoutParam"
        - "$ref": "#/parameters/setParam"
        - "$ref": "#/parameters/exerciseParam"
        - name: comment
          in: formData
          description: Any comment you would like to store for this exercise.
          required: false
          type: string
      responses:
        200:
          description: The updated exercise.
          schema:
            $ref: '#/definitions/Exercise'
        default:
            description: Unexpected error
            schema:
              $ref: '#/definitions/Error'
    delete: # Delete the specified exercise
      summary: Delete an exercise.
      description: Delete the specified Exercise.
      parameters:
        - "$ref": "#/parameters/workoutParam"
        - "$ref": "#/parameters/setParam"
        - "$ref": "#/parameters/exerciseParam"
      responses:
        200:
          description: Exercise deleted.
        default:
            description: Unexpected error
            schema:
              $ref: '#/definitions/Error'

# Model definitions for this API
definitions:
  Workout:
    properties:
      timestamp:
        type: string
        description: The time at which this workout was performed.
      comment:
        type: string
        description: Any additional comments made about this workout.
      exercises:
        type: array
        items:
          $ref: '#/definitions/Exercise'
  Exercise:
    properties:
      comment:
        type: string
        description: Any additional comments made about this workout.
      sets:
        type: array
        items:
          $ref: '#/definitions/Set'
  Set:
    properties:
      reps:
        type: integer
        description: The number of repititions to be performed during this set
      weight:
        type: integer
        description: |
          The weight at which to perform this set's exercise. Will be 0 for
          bodyweight exercises and cardio.
      order:
        type: integer
        description: No idea
      rest:
        type: integer
        description: The duration to rest for before proceeding with the next set.
  ExerciseMeta:
    properties:
      name:
        type: string
        description: The name of this ExerciseMeta
      progress_differential:
        type: float64
        description: The rate at which weight/reps for this excercise should be increased by
      primary_muscle_group:
        type: string
        description: Primary muscle group impacted by this exercise.
      secondary_muscle_group:
        type: string
        description: Secondary muscle group impacted by this exercise.
      category:
        type: string
        description: |
          What type of exercise is this? Will be one of Resistance, Functional,
          or Cardio.
      also_known_as:
        type: string
        description: Aliases for this ExerciseMeta
      mechanics_type:
        type: string
        description: Describes the mechanics of this exercise. Will be either Compound or Isolation.
      muscle_image:
        type: string
        description: A link to a heatmap image of the muscles impacted by this exercise
      guide:
        type: string
        description: A newline separated textual guide to this exercise
      difficulty_level:
        type: string
        description: |
          Indicates the level of skill, on average, required to perform this
          exercise successfully.
      equipment:
        type: string
        description: Free form text describing any equipment required to perform this exercise.
      force:
        type: string
        description: The direction of force applied to perform this exercise.
      type:
        type: string
        description: This ExerciseMeta's type
