---
- name: check if docker is installed
  shell: type docker
  ignore_errors: true
  register: docker_installed

- name: install Docker via curl'd script
  shell: curl -sSL https://get.docker.com/ | sh
  when: docker_installed|failed or upgrade_docker
